
print("loading oled.lua")
dofile("oled.lua")
print("loading variables.lua")
write("","Loading","variables.lua","","")
dofile("variables.lua")
write("","Loading","variables.lua ok","","")
print("loading detectChangeOnPin.lc")
write("","Loading","detectChangeOnPin.lc ...","","")
dofile("detectChangeOnPin.lc")
write("","Loading","detectChangeOnPin.lc ok","","")
print("loading setWifi.lc")
write("","Loading","setWifi.lc ...","","")
dofile("setWifi.lc")
write("","Loading","setWifi.lc ok","","")
print("loading setWebServer.lc")
write("","Loading","setWebServer.lc ...","","")
dofile("setWebServer.lc")
write("","Loading","setWebServer.lc ok","","")
print("loading mqtt.lc")
write("","Loading","mqtt.lc ...","","")
dofile("mqtt.lc")
write("","Loading","mqtt.lc ok","","")
write("Keeper of the Faith","by Terror (2015)","Ready... v1.0","Webserver on",wifi_ip .. "(" .. mode .. ")")
