dofile("oled.lc")
write("","Loading","variables.lua","","")
dofile("variables.lua")
write("","Loading","variables.lua ok","","")
write("","Loading","detectChangeOnPin.lc ...","","")
dofile("detectChangeOnPin.lc")
write("","Loading","detectChangeOnPin.lc ok","","")
write("","Loading","setWifi.lc ...","","")
dofile("setWifi.lc")
write("","Loading","setWifi.lc ok","","")
write("","Loading","setWebServer.lc ...","","")
dofile("setWebServer.lc")
write("","Loading","setWebServer.lc ok","","")
write("Keeper of the Faith","by Terror (2015)","Ready... v1.0","Webserver on",wifi_ip .. "(" .. mode .. ")")
